[project]
name = "finance-assistant"
version = "2.0.0"
description = "Comprehensive financial analysis platform with AI-powered queries, technical analysis, and portfolio optimization"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.116.1",
    "httpx>=0.28.1",
    "pandas>=2.3.1",
    "pydantic>=2.11.7",
    "python-dotenv>=1.1.1",
    "python-multipart>=0.0.20",
    "redis>=6.4.0",
    "uvicorn>=0.35.0",
    "yfinance>=0.2.65",
    "numpy>=1.24.0",
    "scikit-learn>=1.3.0",
    "requests>=2.31.0",
    "python-dateutil>=2.8.2",
    "plotly>=5.15.0",
    "matplotlib>=3.7.0",
    "aiofiles>=23.2.1",
    "asyncio-mqtt>=0.13.0",
    "cachetools>=5.3.0",
    "setuptools>=80.9.0",
]
